fixing tests

diff --git a/.github/workflows/Playwright.yml b/.github/workflows/Playwright.yml
--- a/.github/workflows/Playwright.yml
+++ b/.github/workflows/Playwright.yml
@@ -33,10 +33,15 @@ jobs:
 
       - name: Wait for the app
         run: |
-          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
+          RETRIES=6
+          until curl --output /dev/null --silent --head --fail http://localhost:3000 || [ $((RETRIES--)) -eq 0 ]; do
             echo "Waiting for server..."
-            sleep 2
+            sleep 5
           done
+          if [ $RETRIES -lt 0 ]; then
+            echo "Server failed to start within the timeout period."
+            exit 1
+          fi
         shell: bash
 
       - name: Run your tests
